apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fitness-dev
resources:
  - ../base
secretGenerator:
  - name: fitness-secrets
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: true
